# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run.
on: [push,pull_request,workflow_dispatch]

# A workflow run is made up of one or 69 jobs that can run sequentially or in parallel
jobs:
  # This workflow dsoent contain a single job called "build"
  Android-Armv6:
    name: Android Armv6
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r11c

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.0

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null
          haxelib install lime 7.9.0 --quiet
          haxelib install lime-samples 6.2.0 --quiet
          haxelib install layout 1.2.1 --quiet
          haxelib install openfl-samples 8.7.0 --quiet
          haxelib install flixel-demos 2.7.3 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install flixel-templates 2.6.5 --quiet
          haxelib install flixel-tools 1.5.0 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib install systools 1.1.0 --quiet
          haxelib install box2d 1.2.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel 4.9.0 --quiet
          haxelib install openfl 9.0.1 --quiet
          haxelib git faxe https://github.com/91ebagacm/faxe.git --quiet
          haxelib git polymod https://github.com/91ebagacm/polymod.git --quiet
          haxelib git linc_luajit https://github.com/91ebagacm/linc_luajit.git --quiet
          haxelib git extension-webview https://github.com/91ebagacm/extension-webview.git --quiet
          haxelib git extension-androidtools https://github.com/mcagabe19/extension-androidtools.git

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: |
          haxelib run lime build android --app-version="4.0.0" -armv6
          rm export/release/android/bin/app/build/outputs/apk/debug/*.json

      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: androidBuildarmv6
          path: export/release/android/bin/app/build/outputs/apk/debug

  Android-Armv5:
    name: Android Armv5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r11c

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.0

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null
          haxelib install lime 7.9.0 --quiet
          haxelib install lime-samples 6.2.0 --quiet
          haxelib install layout 1.2.1 --quiet
          haxelib install openfl-samples 8.7.0 --quiet
          haxelib install flixel-demos 2.7.3 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install flixel-templates 2.6.5 --quiet
          haxelib install flixel-tools 1.5.0 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib install systools 1.1.0 --quiet
          haxelib install box2d 1.2.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel 4.9.0 --quiet
          haxelib install openfl 9.0.1 --quiet
          haxelib git faxe https://github.com/91ebagacm/faxe.git --quiet
          haxelib git polymod https://github.com/91ebagacm/polymod.git --quiet
          haxelib git linc_luajit https://github.com/91ebagacm/linc_luajit.git --quiet
          haxelib git extension-webview https://github.com/91ebagacm/extension-webview.git --quiet
          haxelib git extension-androidtools https://github.com/mcagabe19/extension-androidtools.git

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: |
          haxelib run lime build android --app-version="4.0.0" -armv5
          rm export/release/android/bin/app/build/outputs/apk/debug/*.json
        
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: androidBuildarmv5
          path: export/release/android/bin/app/build/outputs/apk/debug
