# This is a basic workflow to help you get started with Actions

name: Debug

# Controls when the action will run.
on: [push,pull_request,workflow_dispatch]

# A workflow run is made up of one or 69 jobs that can run sequentially or in parallel
jobs:
  # This workflow dsoent contain a single job called "build"
  Android-Debug-Arm-32:
    name: Android Debug Arm 32
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r20b

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.0

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null
          haxelib install lime 7.9.0 --quiet
          haxelib install lime-samples 6.2.0 --quiet
          haxelib install layout 1.2.1 --quiet
          haxelib install openfl-samples 8.7.0 --quiet
          haxelib install flixel-demos 2.7.3 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install flixel-templates 2.6.5 --quiet
          haxelib install flixel-tools 1.5.0 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib install systools 1.1.0 --quiet
          haxelib install box2d 1.2.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel 4.9.0 --quiet
          haxelib install openfl 9.0.1 --quiet
          haxelib git faxe https://github.com/91ebagacm/faxe.git --quiet
          haxelib git polymod https://github.com/91ebagacm/polymod.git --quiet
          haxelib git linc_luajit https://github.com/91ebagacm/linc_luajit.git --quiet
          haxelib git extension-webview https://github.com/91ebagacm/extension-webview.git --quiet
          haxelib git extension-androidtools https://github.com/91ebagacm/extension-androidtools.git

      - name: Setup Flixel
        run: haxelib run lime setup flixel

      - name: Set Versions
        run: |
          haxelib set openfl 9.0.1
          haxelib set lime 7.9.0
          haxelib set lime-samples 6.2.0
          haxelib set layout 1.2.1
          haxelib set openfl-samples 8.7.0
          haxelib set flixel-demos 2.7.3
          haxelib set flixel-addons 2.10.0
          haxelib set flixel-templates 2.6.5
          haxelib set flixel-tools 1.5.0
          haxelib set flixel-ui 2.3.3
          haxelib set actuate 1.8.9
          haxelib set systools 1.1.0
          haxelib set box2d 1.2.3
          haxelib set hscript 2.4.0

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: |
          haxelib run lime build android -debug --app-version="4.0.0" -armv7
          rm export/debug/android/bin/app/build/outputs/apk/debug/*.json
        
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: androidBuildDebug32
          path: export/debug/android/bin/app/build/outputs/apk/debug

  Android-Debug-Arm-64:
    name: Android Debug Arm 64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r20b

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.0

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null
          haxelib install lime 7.9.0 --quiet
          haxelib install lime-samples 6.2.0 --quiet
          haxelib install layout 1.2.1 --quiet
          haxelib install openfl-samples 8.7.0 --quiet
          haxelib install flixel-demos 2.7.3 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install flixel-templates 2.6.5 --quiet
          haxelib install flixel-tools 1.5.0 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib install systools 1.1.0 --quiet
          haxelib install box2d 1.2.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel 4.9.0 --quiet
          haxelib install openfl 9.0.1 --quiet
          haxelib git faxe https://github.com/91ebagacm/faxe.git --quiet
          haxelib git polymod https://github.com/91ebagacm/polymod.git --quiet
          haxelib git linc_luajit https://github.com/91ebagacm/linc_luajit.git --quiet
          haxelib git extension-webview https://github.com/91ebagacm/extension-webview.git --quiet
          haxelib git extension-androidtools https://github.com/91ebagacm/extension-androidtools.git

      - name: Setup Flixel
        run: haxelib run lime setup flixel

      - name: Set Versions
        run: |
          haxelib set openfl 9.0.1
          haxelib set lime 7.9.0
          haxelib set lime-samples 6.2.0
          haxelib set layout 1.2.1
          haxelib set openfl-samples 8.7.0
          haxelib set flixel-demos 2.7.3
          haxelib set flixel-addons 2.10.0
          haxelib set flixel-templates 2.6.5
          haxelib set flixel-tools 1.5.0
          haxelib set flixel-ui 2.3.3
          haxelib set actuate 1.8.9
          haxelib set systools 1.1.0
          haxelib set box2d 1.2.3
          haxelib set hscript 2.4.0

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: |
          haxelib run lime build android -debug --app-version="4.0.0" -arm64
          rm export/debug/android/bin/app/build/outputs/apk/debug/*.json
        
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: androidBuildDebug64
          path: export/debug/android/bin/app/build/outputs/apk/debug

  Android-Debug-x86:
    name: Android Debug x86
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r20b

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.0

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null
          haxelib install lime 7.9.0 --quiet
          haxelib install lime-samples 6.2.0 --quiet
          haxelib install layout 1.2.1 --quiet
          haxelib install openfl-samples 8.7.0 --quiet
          haxelib install flixel-demos 2.7.3 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install flixel-templates 2.6.5 --quiet
          haxelib install flixel-tools 1.5.0 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib install systools 1.1.0 --quiet
          haxelib install box2d 1.2.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel 4.9.0 --quiet
          haxelib install openfl 9.0.1 --quiet
          haxelib git faxe https://github.com/91ebagacm/faxe.git --quiet
          haxelib git polymod https://github.com/91ebagacm/polymod.git --quiet
          haxelib git linc_luajit https://github.com/91ebagacm/linc_luajit.git --quiet
          haxelib git extension-webview https://github.com/91ebagacm/extension-webview.git --quiet
          haxelib git extension-androidtools https://github.com/91ebagacm/extension-androidtools.git

      - name: Setup Flixel
        run: haxelib run lime setup flixel

      - name: Set Versions
        run: |
          haxelib set openfl 9.0.1
          haxelib set lime 7.9.0
          haxelib set lime-samples 6.2.0
          haxelib set layout 1.2.1
          haxelib set openfl-samples 8.7.0
          haxelib set flixel-demos 2.7.3
          haxelib set flixel-addons 2.10.0
          haxelib set flixel-templates 2.6.5
          haxelib set flixel-tools 1.5.0
          haxelib set flixel-ui 2.3.3
          haxelib set actuate 1.8.9
          haxelib set systools 1.1.0
          haxelib set box2d 1.2.3
          haxelib set hscript 2.4.0

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: |
          haxelib run lime build android -debug --app-version="4.0.0" -32
          rm export/debug/android/bin/app/build/outputs/apk/debug/*.json
        
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: androidBuildDebug86
          path: export/debug/android/bin/app/build/outputs/apk/debug

  Android-Debug-x86_64:
    name: Android Debug x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r20b

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.0

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 > /dev/null
          haxelib install lime 7.9.0 --quiet
          git clone https://github.com/mcagabe19/lime-ndll-x86_64.git ~/lime-ndll-x86_64
          mv ~/lime-ndll-x86_64/ndll/Android/* ~/haxelib/lime/7\,9\,0/ndll/Android
          haxelib install lime-samples 6.2.0 --quiet
          haxelib install layout 1.2.1 --quiet
          haxelib install openfl-samples 8.7.0 --quiet
          haxelib install flixel-demos 2.7.3 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install flixel-templates 2.6.5 --quiet
          haxelib install flixel-tools 1.5.0 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib install systools 1.1.0 --quiet
          haxelib install box2d 1.2.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel 4.9.0 --quiet
          haxelib install openfl 9.0.1 --quiet
          haxelib git faxe https://github.com/91ebagacm/faxe.git --quiet
          haxelib git polymod https://github.com/91ebagacm/polymod.git --quiet
          haxelib git linc_luajit https://github.com/91ebagacm/linc_luajit.git --quiet
          haxelib git extension-webview https://github.com/91ebagacm/extension-webview.git --quiet
          haxelib git extension-androidtools https://github.com/91ebagacm/extension-androidtools.git

      - name: Setup Flixel
        run: haxelib run lime setup flixel

      - name: Set Versions
        run: |
          haxelib set openfl 9.0.1
          haxelib set lime 7.9.0
          haxelib set lime-samples 6.2.0
          haxelib set layout 1.2.1
          haxelib set openfl-samples 8.7.0
          haxelib set flixel-demos 2.7.3
          haxelib set flixel-addons 2.10.0
          haxelib set flixel-templates 2.6.5
          haxelib set flixel-tools 1.5.0
          haxelib set flixel-ui 2.3.3
          haxelib set actuate 1.8.9
          haxelib set systools 1.1.0
          haxelib set box2d 1.2.3
          haxelib set hscript 2.4.0
          haxelib set format 3.5.0
          haxelib set hxp 1.2.2

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Compile
        run: |
          haxelib run lime build android -debug --app-version="4.0.0" -64
          rm export/debug/android/bin/app/build/outputs/apk/debug/*.json
        
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: androidBuildDebug86_64
          path: export/debug/android/bin/app/build/outputs/apk/debug
